<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * About us view script
 * 
 * @package    Application
 */

$this->headTitle('Kontakt');
$this->pageTitle('Sie haben eine Frage an uns?');

$url = $this->url('application', array(), array(), true);

echo $this->cmsContentBlock('application_about_contact', $url);
