<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * About us view script
 * 
 * @package    Application
 */

$this->headTitle('Impressum');
$this->pageTitle('Impressum und rechtliche Hinweise');

$url = $this->url('application/action', array(), array(), true);

echo $this->cmsContentBlock('application_about_imprint', $url);
