<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * User-Admin update view script
 * 
 * @package    User
 */

$this->headTitle('Benutzer ändern');
$this->pageTitle('Den ausgewählten Benutzer ändern');

$actionUrl = $this->url('user-admin/action', array(), array(), true);

echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
