<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */

$this->headTitle('Server Fehler');
$this->pageTitle('Server Fehler');
?>
<p>Leider hat unser Server einen kleinen Schluckauf und konnte die Anfrage nicht ohne Fehler verarbeiten. Das gesamte Team entschuldigt sich bei Ihnen für diesen Missstand und gelobt Besserung.</p>
<table class="table-images">
	<tbody>
		<tr>
			<td>
			<p style="text-align: center;"><img alt="Luigi" class="thumbnail span2" src="/img/team/luigi.png" /></p>

			<p style="text-align: center;">Luigi Bartoli<br />
			Chef</p>
			</td>
			<td>
			<p style="text-align: center;"><img alt="Francesca" class="thumbnail span2" src="/img/team/francesca.png" /></p>

			<p style="text-align: center;">Francesca Bartoli<br />
			Service</p>
			</td>
			<td>
			<p style="text-align: center;"><img alt="Alessandro" class="thumbnail span2" src="/img/team/alessandro.png" /></p>

			<p style="text-align: center;">Alessandro Altobelli<br />
			Koch</p>
			</td>
			<td>
			<p style="text-align: center;"><img alt="Valentina" class="thumbnail span2" src="/img/team/valentina.png" /></p>

			<p style="text-align: center;">Valentina Rossi<br />
			K&ouml;chin</p>
			</td>
		</tr>
	</tbody>
</table>
<p class="pull-center"><a href="/" class="btn">Zur Startseite</a></p>
<hr />
<div class="alert alert-error">
<h2>Es ist ein interner Server Fehler aufgetreten.</h2>
<p>Bitte später noch einmal versuchen.</p>
</div>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
    <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
        <?php $e = $this->exception->getPrevious(); ?>
        <div class="well">
        <h3>Weitere Informationen</h3>
        <table class="table">
        <tr>
        <th>Exception</th>
        <td><?php echo get_class($this->exception); ?></td>
        </tr>
        <tr>
        <th>Datei</th>
        <td><pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre></td>
        </tr>
        <tr>
        <th>Meldung</th>
        <td><pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre></td>
        </tr>
        <tr>
        <th>Stack&nbsp;Trace</th>
        <td><pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre></td>
        </tr>
        </table>
        </div>
        <?php if ($e) : ?>
            <hr/>
            <div class="well">
            <h3>Vorherige Exceptions</h3>
            <?php while($e) : ?>
                <table class="table">
                <tr>
                <th>Exception</th>
                <td><?php echo get_class($e); ?></td>
                </tr>
                <tr>
                <th>Datei</th>
                <td><pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre></td>
                </tr>
                <tr>
                <th>Meldung</th>
                <td><pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre></td>
                </tr>
                <tr>
                <th>Stack&nbsp;Trace</th>
                <td><pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre></td>
                </tr>
                </table>
                <hr/>
                <?php $e = $e->getPrevious(); ?>
            <?php endwhile; ?>
            </div>
        <?php endif; ?>
    <?php else: ?>
        <h3>Keine Exception vorhanden</h3>
    <?php endif ?>
<?php endif ?>
