<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * User login view script
 * 
 * @package    User
 */
$this->headTitle('Anmelden');
$this->pageTitle('Als Benutzer anmelden');

$actionUrl = $this->url('user/action', array('action' => 'login'));

echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
?>
<hr />
<h3>Sie sind noch nicht angemeldet?</h3>
<?php $url = $this->url('user/action', array('action' => 'register'))?>
<a href="<?php echo $url; ?>" class="btn">Jetzt registrieren</a>