<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Index view script
 * 
 * @package    Application
 */

$this->headTitle('Listings - Kapitel 22');
$this->pageTitle('Listings - Kapitel 22');
?>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing2201">Listing 22.1</a></td>
<td>Aufbau der Datenbank</td>
</tr>
<tr>
<td><a href="/listing/listing2202">Listing 22.2</a></td>
<td><code>BasketEntity</code> stellt Warenkorbdaten bereit</td>
</tr>
<tr>
<td><a href="/listing/listing2203">Listing 22.3</a></td>
<td><code>PositionEntity</code> für die Verarbeitung von Bestellpositionen</td>
</tr>
<tr>
<td><a href="/listing/listing2204">Listing 22.4</a></td>
<td><code>OrderHydrator</code> kümmert sich um Serialisierung/Deserialisierung</td>
</tr>
<tr>
<td><a href="/listing/listing2205">Listing 22.5</a></td>
<td><code>OrderTable</code> setzt <code>OrderHydrator</code> ein</td>
</tr>
<tr>
<td><a href="/listing/listing2206">Listing 22.6</a></td>
<td>Besonderheiten im <code>OrderService</code></td>
</tr>
<tr>
<td><a href="/listing/listing2207">Listing 22.7</a></td>
<td><code>BasketService</code> stellt Zugriff auf Warenkorb bereit</td>
</tr>
<tr>
<td><a href="/listing/listing2208">Listing 22.8</a></td>
<td>Controller-Plugin <code>Basket</code> ermöglicht Zugriff auf <code>BasketService</code></td>
</tr>
<tr>
<td><a href="/listing/listing2209">Listing 22.9</a></td>
<td>View-Helper <code>ShowBasket</code> ermöglicht Ausgabe des Warenkorbs</td>
</tr>
<tr>
<td><a href="/listing/listing2210">Listing 22.10</a></td>
<td>View-Skript <code>small-basket.phtml</code> gibt gekürzten Warenkorb aus</td>
</tr>
<tr>
<td><a href="/listing/listing2211">Listing 22.11</a></td>
<td>View-Skript <code>full-basket.phtml</code> gibt vollständigen Warenkorb aus</td>
</tr>
<tr>
<td><a href="/listing/listing2212">Listing 22.12</a></td>
<td>View-Helper <code>GetOrder</code> holt Bestelldaten</td>
</tr>
<tr>
<td><a href="/listing/listing2213">Listing 22.13</a></td>
<td><code>BasketController</code> zur Bearbeitung eines Warenkorbs</td>
</tr>
<tr>
<td><a href="/listing/listing2214">Listing 22.14</a></td>
<td>View-Skript <code>index.phtml</code> zur Darstellung des Warenkorbs</td>
</tr>
<tr>
<td><a href="/listing/listing2215">Listing 22.15</a></td>
<td>View-Skript <code>create.phtml</code> zum Anlegen einer Bestellung</td>
</tr>
<tr>
<td><a href="/listing/listing2216">Listing 22.16</a></td>
<td>View-Skript <code>thanks.phtml</code> zur Darstellung einer Bestellbestätigung</td>
</tr>
<tr>
<td><a href="/listing/listing2217">Listing 22.17</a></td>
<td>Neue <code>basketAction()</code> Aktionsmethode im <code>PizzaController</code></td>
</tr>
<tr>
<td><a href="/listing/listing2218">Listing 22.18</a></td>
<td>Button zum Ablegen in Warenkorb in View-Skript eingebaut</td>
</tr>
</tbody>
</table>
