<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 22.12 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 22.12');
$this->pageTitle('Listing 22.12');
?>
<h3>View-Helper <code>GetOrder</code> holt Bestelldaten</h3>
<pre>
&lt;?php
namespace Shop\View\Helper;

use Shop\Entity\OrderEntityInterface;
use Shop\Service\OrderServiceInterface;
use Zend\View\Helper\AbstractHelper;

class GetOrder extends AbstractHelper
{
    protected $orderService;

    public function __construct(OrderServiceInterface $orderService)
    {
        $this->setOrderService($orderService);
    }

    public function setOrderService(OrderServiceInterface $orderService = null)
    {
        $this->orderService = $orderService;
        return $this;
    }
    
    public function getOrderService()
    {
        return $this->orderService;
    }
    
    public function __invoke($id)
    {
        return $this->getOrderService()->fetchSingleById($id);
    }
}
</pre>
