<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 22.14 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 22.14');
$this->pageTitle('Listing 22.14');
?>
<h3>View-Skript <code>index.phtml</code> zur Darstellung des Warenkorbs</h3>
<pre>
&lt;?php
$this-&gt;headTitle('Warenkorb');
$this-&gt;pageTitle('Ihr Warenkorb');

$basket = $this-&gt;basket; /* @var $basket BasketEntity */

echo $this-&gt;shopShowBasket('full');
?&gt;
&lt;?php if (!$basket-&gt;isEmpty()) : ?&gt;
&lt;?php if ($this-&gt;userIsAllowed('order', 'create')): ?&gt;
&lt;?php $urlOrder = $this-&gt;url('shop/order/action', array('action' =&gt; 'create')); ?&gt;
&lt;h4&gt;Sie sind angemeldet und können nun bestellen.&lt;/h4&gt; 
&lt;p&gt;
&lt;a href="&lt;?php echo $urlOrder; ?&gt;" class="btn"&gt;Bestellung ausführen&lt;/a&gt;
&lt;/p&gt;
&lt;?php else: ?&gt;
&lt;?php $urlLogin    = $this-&gt;url('user', array('action' =&gt; 'login')); ?&gt;
&lt;?php $urlRegister = $this-&gt;url('user', array('action' =&gt; 'register')); ?&gt;
&lt;h4&gt;Sie sind nicht angemeldet.&lt;/h4&gt; 
&lt;p&gt;
&lt;a href="&lt;?php echo $urlLogin; ?&gt;" class="btn"&gt;Anmelden&lt;/a&gt; 
&lt;a href="&lt;?php echo $urlRegister; ?&gt;" class="btn"&gt;Jetzt registrieren&lt;/a&gt;
&lt;/p&gt;
&lt;?php endif; ?&gt;
&lt;?php endif; ?&gt;
</pre>
