<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 22.1 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 22.1');
$this->pageTitle('Listing 22.1');
?>
<h3>Aufbau der Datenbank</h3>
<pre>
CREATE TABLE orders (
    id integer primary key, 
    cdate datetime, 
    status varchar(8), 
    positions text, 
    comments text, 
    user_id integer, 
    FOREIGN KEY(user_id) REFERENCES users(id)
);
</pre>
