<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch 'Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung'
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 22.4 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 22.4');
$this->pageTitle('Listing 22.4');
?>
<h3><code>OrderHydrator</code> kümmert sich um Serialisierung/Deserialisierung</h3>
<pre>
&lt;?php
namespace Shop\Hydrator;

use Zend\Serializer\Serializer;
use Zend\Stdlib\Hydrator\HydratorInterface;

class OrderHydrator implements HydratorInterface
{
    public function extract($object)
    {
        $data = $object->getArrayCopy();
        $data['positions'] = Serializer::serialize($data['positions']);
        
        return $data;
    }

    public function hydrate(array $data, $object)
    {
        $data['positions'] = Serializer::unserialize($data['positions']);
        
        $object->exchangeArray($data);
                   
        return $object;
    }
}
</pre>
