<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 22.16 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 22.16');
$this->pageTitle('Listing 22.16');
?>
<h3>View-Skript <code>create.phtml</code> zum Anlegen einer Bestellung</h3>
<pre>
&lt;?php
$this-&gt;headTitle('Bestellung ausführen');
$this-&gt;pageTitle('Eine Bestellung ausführen');

$this-&gt;headScript()-&gt;appendFile(
    $this-&gt;basePath() . '/js/ckeditor/ckeditor.js', 'text/javascript'
);

$identity = $this-&gt;identity; /* @var $identity UserEntity */
?&gt;
&lt;h3&gt;Ihr Warenkorb&lt;/h3&gt;
&lt;?php echo $this-&gt;shopShowBasket('full'); ?&gt;
&lt;h3&gt;Ihre Bestellung&lt;/h3&gt;
&lt;table class="table table-data"&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;th&gt;E-Mail-Adresse&lt;/th&gt;
&lt;td&gt;&lt;?php echo $identity-&gt;getEmail(); ?&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;th&gt;Name&lt;/th&gt;
&lt;td&gt;
&lt;?php echo $identity-&gt;getFirstname(); ?&gt; &lt;?php echo $identity-&gt;getLastname(); ?&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;?php 
$actionUrl = $this-&gt;url(
    'shop/order/action', array('action' =&gt; 'create'), array(), true
);
echo $this-&gt;showForm($this-&gt;form, $actionUrl, 'form-horizontal');
</pre>
