<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 22.1 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 22.1');
$this->pageTitle('Listing 22.1');
?>
<h3>Aufbau der Datenbank</h3>
<pre>
CREATE TABLE orders (
    id integer primary key, 
    cdate datetime, 
    status varchar(8), 
    positions text, 
    comments text, 
    user_id integer, 
    FOREIGN KEY(user_id) REFERENCES users(id)
);
</pre>
