<?php
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Sidebar view script
 * 
 * @package    Application
 */

$url = $this->url(null, array(), true);

if ($this->getHelperPluginManager()->has('userShowWidget')) {
    echo $this->userShowWidget();
}

if ($this->getHelperPluginManager()->has('shopShowBasket')) {
    echo $this->shopShowBasket();
}
?>
<div class="well">
<?php echo $this->cmsContentBlock('application_sidebar_box1', $url); ?>
</div>
<div class="well">
<h4 class="pull-center">Buch Website</h4>
<p>Die Buchwebsite mit aktuellen Infos zum Buch, Blog &amp; Linkcodes.</p>
<p class="pull-center"><a class="btn btn-primary" href="http://www.zendframeworkbuch.de/">Zur Buch Website &raquo;</a></p>
</div>
<div class="well">
<p class="pull-center"><a href="http://www.zfforum.de/zend-framework-2-buch/" target="_blank"><img src="/img/stuff/zfforum.jpg"></a></p>
<p class="pull-center"><a class="btn btn-primary" href="http://www.zfforum.de/zend-framework-2-buch/" target="_blank">Zum Support Forum &raquo;</a></p>
</div>
<div class="well">
<p class="pull-center"><a target="_blank" href="http://www.zendframeworkschulung.de/"><img src="http://www.zendframeworkschulung.de/img/logo.png"></a></p>
<p>Stärken Sie Ihr Know-how und buchen Sie eine Zend Framework 2 Schulung in Ihrer Nähe.</p>
<p class="pull-center"><a class="btn btn-primary" target="_blank" href="http://www.zendframeworkschulung.de/">Zend Framework Schulung 2 »</a></p>
</div>
