<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Pizza
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Pizza-Admin create view script
 * 
 * @package    Pizza
 */

$this->headTitle('Pizza anlegen');
$this->pageTitle('Einen neue Pizza anlegen');

$this->headScript()->appendFile(
    $this->basePath() . '/js/ckeditor/ckeditor.js', 'text/javascript'
);

$actionUrl = $this->url('pizza-admin/action', array('action' => 'create'));

echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
