<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Shop
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * namespace definition and usage
 */
use Shop\Entity\OrderEntity;
use User\Entity\UserEntity;

/**
 * Order update view script
 * 
 * @package    Shop
 */

$this->headTitle('Bestellung ausführen');
$this->pageTitle('Eine Bestellung ausführen');

$this->headScript()->appendFile(
    $this->basePath() . '/js/ckeditor/ckeditor.js', 'text/javascript'
);

// set identity entity
$identity = $this->identity; /* @var $identity UserEntity */
?>
<h3>Ihr Warenkorb</h3>
<?php echo $this->shopShowBasket('full'); ?>
<h3>Ihre Bestellung</h3>
<table class="table table-data">
<tbody>
<tr>
<th>E-Mail-Adresse</th>
<td><?php echo $identity->getEmail(); ?></td>
</tr>
<tr>
<th>Name</th>
<td>
<?php echo $identity->getFirstname(); ?> <?php echo $identity->getLastname(); ?>
</td>
</tr>
</tbody>
</table>
<?php 
$actionUrl = $this->url(
    'shop/order/action', array('action' => 'create'), array(), true
);
echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
