<?php 
/**
 * ZF2 Buch Kapitel 22
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Comment
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * namespace definition and usage
 */
use Comment\Entity\CommentEntity;

/**
 * Comment-Admin index view script
 *
 * @package    Comment
 */

$this->headTitle('Kommentare verwalten');
$this->pageTitle('Kommentare verwalten');

?>
<table class="table table-striped table-bordered table-hover table-condensed">
<thead>
<tr>
<th>Datum</th>
<th>Seite</th>
<th>Name</th>
<th>Status</th>
<th>Spam</th>
<th width="130">Optionen</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->commentList as $comment) : /* @var $comment CommentEntity */ ?>
<?php
$urlShow = $this->url(
    'comment-admin/action', array('action' => 'show', 'id' => $comment->getId())
);
$urlEdit = $this->url(
    'comment-admin/action', array('action' => 'update', 'id' => $comment->getId())
);
$urlDelete = $this->url(
    'comment-admin/action', array('action' => 'delete', 'id' => $comment->getId())
);
$urlComment = $comment->getUrl();
?>
<tr>
<td><?php echo $this->date($comment->getCdate()); ?></td>
<td><a href="<?php echo $urlComment; ?>"><?php echo $urlComment; ?></a></td>
<td><?php echo $comment->getName(); ?></td>
<td><?php echo $comment->getStatusName(); ?></td>
<td><?php echo $this->spamCheck()->classify($comment->getFulltext(), 4); ?></td>
<td>
<a href="<?php echo $urlShow; ?>" class="btn"><i class="icon-search"></i></a>
<a href="<?php echo $urlEdit; ?>" class="btn"><i class="icon-pencil"></i></a>
<a href="<?php echo $urlDelete; ?>" class="btn"><i class="icon-trash"></i></a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php
echo $this->paginationControl(
    $this->commentList, 'Sliding', 'pagination/sliding', 
    array('route' => 'comment-admin/page')
);
?>
